const data = [
  {
    id: 1,
    first_name: "Melinde",
    last_name: "Llorens",
    email: "mllorens0@unc.edu",
    img: "http://dummyimage.com/107x100.png/ff4444/ffffff",
    content: "iterate open-source architectures",
  },
  {
    id: 2,
    first_name: "Dominique",
    last_name: "Worwood",
    email: "dworwood1@de.vu",
    img: "http://dummyimage.com/238x100.png/dddddd/000000",
    content: "repurpose back-end communities",
  },
  {
    id: 3,
    first_name: "Mata",
    last_name: "Northill",
    email: "mnorthill2@liveinternet.ru",
    img: "http://dummyimage.com/131x100.png/cc0000/ffffff",
    content: "integrate killer content",
  },
  {
    id: 4,
    first_name: "Skye",
    last_name: "Iacovo",
    email: "siacovo3@geocities.com",
    img: "http://dummyimage.com/201x100.png/5fa2dd/ffffff",
    content: "empower real-time metrics",
  },
  {
    id: 5,
    first_name: "Burr",
    last_name: "Kilbourn",
    email: "bkilbourn4@webmd.com",
    img: "http://dummyimage.com/229x100.png/cc0000/ffffff",
    content: "reintermediate revolutionary platforms",
  },
  {
    id: 6,
    first_name: "Harcourt",
    last_name: "Peppin",
    email: "hpeppin5@loc.gov",
    img: "http://dummyimage.com/222x100.png/ff4444/ffffff",
    content: "incubate cross-media paradigms",
  },
  {
    id: 7,
    first_name: "Roslyn",
    last_name: "Pauwel",
    email: "rpauwel6@webnode.com",
    img: "http://dummyimage.com/242x100.png/ff4444/ffffff",
    content: "empower web-enabled platforms",
  },
  {
    id: 8,
    first_name: "Feodora",
    last_name: "Phillip",
    email: "fphillip7@admin.ch",
    img: "http://dummyimage.com/102x100.png/5fa2dd/ffffff",
    content: "whiteboard wireless schemas",
  },
  {
    id: 9,
    first_name: "Preston",
    last_name: "Coolahan",
    email: "pcoolahan8@apache.org",
    img: "http://dummyimage.com/158x100.png/ff4444/ffffff",
    content: "generate end-to-end web-readiness",
  },
  {
    id: 10,
    first_name: "Celisse",
    last_name: "Cicculi",
    email: "ccicculi9@abc.net.au",
    img: "http://dummyimage.com/118x100.png/5fa2dd/ffffff",
    content: "productize visionary partnerships",
  },
];
module.exports = data;
